[gcp_service_account]
type = "service_account"
project_id = "app-financas-464017"
private_key_id = "7c966e0455810b7fa03a4072ec3d50c7dd654312"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC1/wg5CIq0MZZi
Q/ZaDRIHXW99VLqXhu++bqZ3TSWfMLlIuayGUa7B76t/qen7kjsU4DdM5bs7uwFH
eqNsGlEFdYUl1s3IuGDX5FrQE3GjXTkZQa4o33MfB/XtMSvdv8Md4L+c4htG32Df
AwxbhBZalCaFdETs+WO43zGjeYHncpAgHliteZM0KwUvsxmjvimZWjGauIK6t3MW
B4JgatOxf/CJsF3LCv2+udn5QdeRGkL82jQJ46k7nI4uMaTTRhB8qiIFBpD/HfPR
UaDGsfis1sTQU9vqvsgPHQoCsigHtNDyGSFVpBtgBlIhrcZGejFvqKTnN2guPNS4
LB9d8CUPAgMBAAECggEAJ/Icq2wBCbDymYniOfyxbtVmwaMFu3l+CJW/yuKvdcPb
fydlwyuNiHqi8Ufpl/KOLjRSXvnzgRY4Hyi/Utxp2SFkwpvlmf9CHlC8T/xcjmdJ
P45nfAgje/Wi2FdZEfhjipzIYdZM917TI8/G+BVDVMk8tUECWeMZLLwsaH2kchiW
/jRdRg2R7hBiEDijYyDNWVVB3nYga/Vkh8k9p2ld7sf9QFuKoxrLMImYW+XSKEdt
JxfBUFhMeb/Cie/M5SQChppPfl/eCBbgBEThcoQjdTUblq+BIP3YJC3QZx8cQBFG
ZiDYPRMlwwa0A5y4VOJQBFeuCYV2itGAqo7AKopMqQKBgQD3g05MqwaaZ6qMD6Fj
1CbDMoe2obsU8/AnC3JOlVfPLBGASRs4PS1aCRH9T4eVaRM/FeRwMG3dynAsAlO0
69hVFwRGFQhnGi2Ts9aYz6Msrw7Fu3uK0ac84ss7KK5pw03HlDeF5/Y8CJ+Xe1UC
tppvOx1TQR14+ZwQE4dwRk0lOQKBgQC8PJ0oLv9j1gtZaMZkQrdmOKVqOMh8Ke2z
+OWQwLmZiEV6b1Ivkjx00VMrDwG4lZMvY37mpkq8+zF8b6ZA5h9MR6dw+8bhD6T1
hJI3d4hHeB2+5D1qYzUw44x3GuAUmNJhIAhYM7Lk4c8EtwuEbzbQZ4mvCyb8wMBZ
XLWmO7GkhwKBgCKHwAm0JnSuF734hESAGXRL/WD+STJQIeXgk+7gqOJvPHXQPSro
ZgZUk5zqVnkCsruvWzJHn1w83M9W98SazpB4aJE6Z/SyUz9y7HJfLV2TgpUVZdPl
EdbNsRqsv0BkDdrVE7XruY+AiHtCqoZ5YSw5bArsX6c784jOoCuKM0MJAoGBAJLR
wE6wYZjQQafqNhvLgdrkQfkY8x8NYQ8oCn6eI+WhyXdWzsa2DBudjX4fRVtgpx2m
QDvM5qyCTLXfK9Cg7TaFCQ/yAcxXdHXfgmBrBkugX6sdwN1zJfDM+ymHN9I45JbG
8ltBb75gdiUaVIxmZl2k9Foom6829JB+5FwVYViPAoGBAKKVzuK6qwS9PtoWFdFf
3xD6Eb0mrxMOFhC78sBba1BksDkRJ9xx7ufIWuxHzgblxTSSAt1fD/lBNZOf2T/F
F+Z+9B5RaqOABS7E5rdN4AQOB+yHs860biwIqJx6Zg15zrAHl4nC+un/ULafKjpR
29u3krfHpiiBv3hG+4sYiCJy
-----END PRIVATE KEY-----
"""
client_email = "streamlit-app-service@app-financas-464017.iam.gserviceaccount.com"
client_id = "117668091234212654650"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-app-service%40app-financas-464017.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
